# Generated by Django 5.2 on 2025-04-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='notes',
            field=models.ManyToManyField(null=True, related_name='tags', to='notes.note'),
        ),
    ]
